#!/bin/bash
# Copyright (c) 2011, Terry Meacham <terry.t.meacham@gmail.com>
# Copyright (c) 2011-2013, Doug Goldstein <cardoe@cardoe.com>
#
# Based on svdiff script by Terry Meacham
#
# Released under the BSD 2-clause license

if [[ $# -ne 2 ]]; then
    echo "usage: $0 [svnpath to trunk] [svnpath to branch]"
    exit 1;
fi

base_dir=$(mktemp --directory --tmpdir=/var/tmp)
review_stub=$(basename $2)
review_stub=$(echo ${review_stub} | sed -e 's/@/_/')
trunk_stub=$(basename $1)
trunk_stub=$(echo ${trunk_stub} | sed -e 's/@/_/')
review="${base_dir}/${review_stub}"
trunk="${base_dir}/${trunk_stub}"

# Removes what was previously in the review directory
rm -rf ${base_dir}

# Checks out the branch to review
echo "Checking out $(basename $2) for review..."
svn export --force --ignore-externals $2 ${review} > /dev/null
if [ $? -ne 0 ]; then
    echo "Failed to checkout $2 to ${review}"
    exit 1
fi
echo "Done!"

echo "Checking out $(basename $1)..."
svn export --force --ignore-externals $1 ${trunk} > /dev/null
if [ $? -ne 0 ]; then
    echo "Failed to checkout $2 to ${trunk}"
    exit 1
fi
echo "Done!"

meld "${trunk}" "${review}"

rm -rf "${base_dir}"
echo "Cleaned up"

